BIN = shads
CC = g++
FLAGS = -Wall -pedantic
SYS_LIB = -lGL -lGLEW -lglfw -lassimp 
SRC = main.cpp gl_utils.cpp obj_parser.cpp maths_funcs.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}
